---
# - name: add the rabbitmq official repo
#   become: true
#   apt_repository:
#     repo: "deb http://www.rabbitmq.com/debian/ testing main"
#     state: present

# - name: add the rabbitmq public key
#   become: true
#   apt_key:
#     url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
#     state: present

- name: update the apt cache
  become: true
  apt:
    update_cache: true

- name: install rabbitmq-server
  become: true
  apt:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  become: true
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: enable web management for rabbit
  become: true
  command: rabbitmq-plugins enable rabbitmq_management
